config/routes.rb
Rails.application.routes.draw do
  devise_for :logins

  root 'home#index'
  resources :users
  resources :posts
  resources :comments
  delete 'users/:id' => 'users#delete'
  resources :logins

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	belongs_to :login
	validates :tresc, :login_id, :post_id, presence: true
end

app/models/login.rb
class Login < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :login
	has_many :comments
	validates :autor, :login_id, :tresc, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
	validates :name, :age, presence: true
	validates :name, format: /[A-Z][a-z]*/
end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController <ApplicationController
	before_action :authenticate_login!, only: [:destroy, :new, :create, :edit]
	before_action :make_sure_its_mine, only:[:destroy, :edit]
	def show
		@comment=Comment.find(params[:id])
	end
    def new
		@comment=Comment.new
		# @post=Post.find(params[:id])
		@post_id=params[:post_id]
	end

	def create
		@comment=Comment.new comment_params
		if @comment.save
			redirect_to (Post.find(@comment.post_id)), notice: "Utworzono"
		else
			render 'new'
		end
	end
	def edit
		@comment = Comment.find params[:id]
	end

	def update
		@comment=Comment.find(params[:id])
		if @comment.update(comment_params)
			redirect_to Post.find(@comment.post_id), notice: "Everything is fine!"
		else
			render 'edit'
		end	
	end 
	def destroy
		@comment=Comment.find(params[:id])
		@comment.destroy
		redirect_to Post.find(@comment.post_id), alert: "usunieto"
    end
	private
	def comment_params
		params.require(:comment).permit(:tresc, :login_id, :post_id)
	end
	private
		def make_sure_its_mine
			unless current_login.id==Comment.find(params[:id].to_i).login.id
				redirect_to root_url, alert: "To nie twoj post!"
			end
			true
		end	

end

app/controllers/home_controller.rb
class HomeController <ApplicationController
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	before_action :authenticate_login!
	before_action :make_sure_its_mine, only:[:show]
	before_action :make_sure_its_host, only:[:index]

	def show
		@login=current_login
	end

	def index
		@login=Login.all
	end

	private
		def make_sure_its_mine
			unless current_login.id==params[:id].to_i
				redirect_to root_url, alert: "To nie twoje konto"
			end
			true
		end
	private
		def make_sure_its_host
			unless current_login.id==1
				redirect_to root_url, alert: "nie jestes hostem!"
			end
			true
		end
end

app/controllers/posts_controller.rb
class PostsController <ApplicationController
	before_action :authenticate_login!, only: [:destroy, :new, :create, :edit]
	before_action :make_sure_its_mine, only:[:destroy, :edit]
	def index
		@post= Post.all
	end

	def show
		@post= Post.find(params[:id])
	end

	def destroy
		@post=Post.find(params[:id])
		@post.destroy
		redirect_to root_url, alert: "usunieto"
    end

    def new
		@post=Post.new
	end

	def create
		@post=Post.new post_params

		if @post.save
			redirect_to root_url, notice: "Utworzono"
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find params[:id]
	end

	def update
		@post=Post.find(params[:id])
		if @post.update(post_params)
			redirect_to root_url, notice: "Everything is fine!"
		else
			render 'edit'
		end	
	end 

	private
	def post_params
		params.require(:post).permit(:tresc, :autor, :login_id)
	end
	private
		def make_sure_its_mine
			unless current_login.id==Post.find(params[:id].to_i).login.id
				redirect_to root_url, alert: "To nie twoj post!"
			end
			true
		end	
end

app/controllers/users_controller.rb
class UsersController <ApplicationController
	def index
		@user= User.all
	end

	def show
		@user= User.find(params[:id])
	end
	def destroy
		@user=User.find(params[:id])
		@user.destroy
		redirect_to root_url, alert: "usunieto"
	end

	def new
		@user=User.new
	end

	def create
		@user=User.new user_params

		if @user.save
			redirect_to root_url, notice: "Utworzono"
		else
			render 'new'
		end
	end

	def edit
		@user = User.find params[:id]
	end

	def update
		@user=User.find(params[:id])
		if @user.update(user_params)
			redirect_to root_url, notice: "Everything is fine!"
		else
			render 'edit'
		end
	end 

	private
	def user_params
		params.require(:user).permit(:name, :age)
	end
end
#http://stackoverflow.com/questions/19373229/rails-4-unknown-action-the-action-destroy-could-not-be-found-for-postscontro

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<h1> Comment editor </h1>
<%= form_for(@comment) do |f| %>
<ul>
<% @comment.errors.full_messages.each do |err| %>
	<li><%= err %> </li>
<%end%>
</ul>
	<%= f.label :tresc %>
	<%= f.text_field :tresc %>
	<%= f.hidden_field :login_id, value: current_login.id %>

	<%= f.submit "EDIT!" %>
	<% end %>

app/views/comments/new.html.erb
<%= form_for(@comment) do |f| %>
<ul>
<% @comment.errors.full_messages.each do |err| %>
	<li><%= err %> </li>
<%end%>
</ul>
	<%= f.label :tresc %>
	<%= f.text_field :tresc %>
	<%= f.hidden_field :post_id, value: @post_id %>
	<%= f.hidden_field :login_id, value: current_login.id %>
	<%= f.submit "Add!" %>
	<% end %>

app/views/comments/show.html.erb
<h1> One comment </h1>
<%= @comment.tresc %>
<p>login:
<%= @comment.login.email %>
</p>
<p>do postu:
	<%= @comment.post.tresc %>
</p>
<p>
	<%= link_to "Main page", root_path %>
</p>

app/views/home/index.html.erb
<p class = "center">
	<%=link_to "Add new post!", new_post_path, :class => "btn btn-primary" %>
</p>
<p class = "center">
	<%=link_to "Posts list", posts_path, :class => "btn btn-primary" %>
</p>
<hr></hr>
<p class="center">
	<%=link_to "Users list (admin only)", logins_path, :class => "btn btn-primary" %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=render 'layouts/partials/gora' %>
<%if alert %>
<p>Uwaga: <%=alert %></p>
<%elsif notice %>
<p>Ok: <%=notice %> </p>
<%end%>



<%= yield %>

</body>
</html>

app/views/layouts/partials/_gora.erb
	<% if current_login %>
<h1> Cześć <%=current_login.email%> </h1> 
<%= link_to "twoj panel", login_path(current_login.id), :class => "btn btn-primary"%>
<%= link_to "Sign out!", destroy_login_session_path, :class => "btn btn-danger pull-right", method: :delete %>
<%else%>
<h1> Czesc nieznajomy </h1>
	<%=link_to "Registration", new_login_registration_path, :class => "btn btn-primary" %>
	<%= link_to "Sign in!", new_login_session_path, :class => "btn btn-success pull-right" %>
<%end%>

app/views/logins/index.html.erb
<h1>Welcome admin! </h1>
<h1>Users list: </h1>
<ol>
<% @login.each do |login| %>
	<li>
		<%= login.email %>
	</li>
	<%end%>
</ol>

app/views/logins/show.html.erb
<h1> Twoj panel: </h1>
<%=@login.email %>
<hr></hr>
<ul>
	<li><%= link_to "logout", destroy_login_session_path, method: :delete%> </li>
	<li><%= link_to "edit or delete account" , edit_login_registration_path %> </li>
</ul>
<hr></hr>
<h3> Your posts: </h3>
<ul>
	<%@login.posts.each do |post| %>
	<li>
		<%= post.tresc %>
		<%= link_to "show me", post_path(post.id) %>
	</li>
	<%end%>
</ul>

app/views/posts/edit.html.erb
<h1> User editor </h1>
<%= form_for(@post) do |f| %>
<ul>
<% @post.errors.full_messages.each do |err| %>
	<li><%= err %> </li>
<%end%>
</ul>
	<%= f.label :tresc %>
	<%= f.text_field :tresc %>
	<%= f.label :autor %>
	<%= f.text_field :autor %>
	<%= f.hidden_field :login_id, value: current_login.id %>

	<%= f.submit "EDIT!" %>
	<% end %>

app/views/posts/index.html.haml
%h1 Posts list
%ul
	-@post.each do|post|
		%li
			=post.tresc
		
		=link_to "add comment", new_comment_path(post_id: post.id)	
		=link_to "usun", post_path(post), method: :delete
		= link_to "edit", edit_post_path(post)
		=link_to "show", post_path(post)
		%ul
			-post.comments.each do |comment|
				%li
					=comment.tresc
				=link_to "show", comment_path(comment)
				=link_to "delete", comment_path(comment), method: :delete
				=link_to "edit", edit_comment_path(comment)

= link_to "Add post", new_post_path

app/views/posts/new.html.erb
<%= form_for(@post) do |f| %>
<ul>
<% @post.errors.full_messages.each do |err| %>
	<li><%= err %> </li>
<%end%>
</ul>
	<%= f.label :tresc %>
	<%= f.text_field :tresc %>
	<%= f.label :autor %>
	<%= f.text_field :autor %>
	<%= f.hidden_field :login_id, value: current_login.id %>
	<%= f.submit "Add!" %>
	<% end %>

app/views/posts/show.html.erb
<h1> One post </h1>
<%= @post.tresc %>
<p>login:
<%= @post.login.email %> </p>
<h1>Comments to this post </h1>
<ul>
	<% @post.comments.each do |comment| %>
	<li> 
		<%= comment.tresc  %> 
		<%= link_to "Edit", edit_comment_path(comment) %>
		<%= link_to "Delete", comment_path(comment), method: :delete %>
		<%= link_to "Show", comment_path(comment) %>
	</li>
	<% end %>
</ul>
<%= link_to "usun", post_path(@post.id), method: :delete %>
<%= link_to "next", post_path(@post.id.next) %>
<p>
	<%= link_to "Main page", root_path %>
</p>

app/views/users/edit.html.erb
<h1> User editor </h1>
<%= form_for(@user) do |f| %>
<ul>
<% @user.errors.full_messages.each do |err| %>
	<li><%= err %> </li>
<%end%>
</ul>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :age %>
	<%= f.text_field :age %>
	<%= f.submit "EDIT!" %>
	<% end %>

app/views/users/index.html.erb
<h1>User list </h1>
<ul>
	<% @user.each do |user| %>
	<li> 
		<%= user.name  %> 
		<%= user.age  %> 
		<%= link_to "Edit", edit_user_path(user) %>
		<%= link_to "Delete", user_path(user), method: :delete %>
		<%= link_to "Show", user_path(user) %>
	</li>
	<% end %>
</ul>

<p>
	<%= link_to "Posts", posts_path %>
</p>
<p>
	<%= link_to "Add user", new_user_path %>
</p>

app/views/users/new.html.erb
<h1> Add User! </h1>
<%= form_for(@user) do |f| %>
<ul>
<% @user.errors.full_messages.each do |err| %>
	<li><%= err %> </li>
<%end%>
</ul>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :age %>
	<%= f.text_field :age %>
	<%= f.submit "Add!" %>
	<% end %>

app/views/users/show.html.erb
<h1> One user </h1>
<%= @user.name %>
<%= link_to "usun", user_path(@user.id), method: :delete %>
<%= link_to "next", user_path(@user.id.next) %>
<p>
	<%= link_to "Main page", root_path %>
</p>
<h1> User's posts </h1>
<ul>
	<% @user.posts.each do |post| %>
	<li> 
		<%= post.tresc %> 
		<%= link_to "usun", post_path(post), method: :delete %>
		<%= link_to "edit", edit_post_path(post)%>
	</li>
	<% end %>
</ul>
<%= link_to "Add post", new_post_path %>
<h1> User's comments </h1>
<ul>
	<% @user.comments.each do |comment| %>
	<li> 
		<%= comment.tresc %> 
	</li>
	<% end %>
</ul>